services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile

    envVars:
      - key: N8N_PORT
        value: ${PORT}
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        value: n8n-bqay.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n-bqay.onrender.com/
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-bqay.onrender.com/
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # EXACT names; no spaces
      - key: NODE_FUNCTION_ALLOW_EXTERNAL
        value: pdf-lib,@google-cloud/documentai,fast-levenshtein
      - key: NODE_PATH
        value: /usr/local/lib/node_modules
      - key: TZ
        value: Asia/Bangkok

      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/gcp-sa.json

      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: true

    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 10
